### PR TITLE
Fixed the unicode issue.

### PR DESCRIPTION
**Pull request by mrgigabyte**
Earlier it used to respond like:  ØªÙ Ø±Ø¨Ø§Øª ÚØª Ù  when it encountered a unicode character, now it wont.

### CODE REVIEW

**Comment by folz** [comment]
I just saw this, sorry. Quick question, why did you pick the latin-1 encoding?

**Comment by mrgigabyte** [comment]
well i was just looking up for a solution i just tried encoding it in latin, i just dont really have a reason for this but this just works fine anyway. Might not be the easiest or the smartest way but yes something that can be implemented imo

**Comment by folz** [comment]
Merged! I freely confess I have no idea why this works, so if things start to break in mysterious ways, this is probably a good PR to revert. But since it seems to work for now -- so let's merge it.

**Comment by folz** [comment]
Version 1.1.0 is now live on pypi and you're added to the contributors list :) thanks for the PR!

**Pull request merged**
