### PR TITLE
voice recognition

### PR DESCRIPTION
**Pull request by AkashMalhotra**
K so I'm kinda new to forking someone's project. I think i added my commit to the master branch, not sure if that was what i'm supposed to do. Anyways, i forked your cleverbot api and made a new file with voice recognition, so user can talk to cleverbot with his voice=)

### CODE REVIEW

**Comment by AkashMalhotra** [comment]
So  is my commit going to be merged?

**Comment by ionuthulub** [comment]
Before I merge it rename the file to "voice_recognition.py" and move it ot the examples folder. 
Also, run flake8 on it and correct ALL the errors and warnings that it will generate before making a pull request.

**Comment by ionuthulub** [comment]
And one more thing. It would be nice if you can write some unit tests for it too.

**Comment by AkashMalhotra** [comment]
KK i'll do it ina  few days, going out of town for a bit. Also, what does it mean when you closed the pull request?

**Comment by ionuthulub** [comment]
It means I rejected it. I didn't merge it into the repo, but do the changes I said and I will.

**Pull request closed without merging**
