### PR TITLE
Shifted to boibot 

### PR DESCRIPTION
**Pull request by mrgigabyte**
After digging a bit and finding appropriate results on internet, I have made certain changes to an old fork. This apparently works like a charm, rest lies up to you if you want to merge this.

### CODE REVIEW

**Comment by folz** [comment]
I unfortunately don't have the time right now to look into this so I'm going to add you as a repo owner and let you take care of this. Could you please version-bump to 2.1.0 before merging in? Thanks!

**Comment by EhsanKia** [comment]
I disagree with this change. It's changing the bot to use an entirely other AI, which may or may not be anywhere as good as cleverbot (who's had over a decade of learning from talking to online users).

I think making a separate library for biobot would be great, but shifting a library called "cleverbot" to use a completely different AI makes no sense at all...

**Comment by folz** [comment]
That's a fair point, but currently this library doesn't work at all. I'm working on migrating to wrap the official API but in the meantime I feel this is an OK stopgap measure.

The bots are built by the same company and (according to their website) trained on the same data. Plus, when I played around with boibot, its responses are similar to what I'd expect from Cleverbot.

I'm open to alternative ideas - what do you think would be a good way to address (1) broken package vs (2) not OG Cleverbot?

**Comment by folz** [comment]
(alternatively, if you wanted to beat me to the PR, I wouldn't mind either)

**Comment by EhsanKia** [comment]
The code posted by @millerhooks worked fine when I tried it last night:
https://gist.github.com/millerhooks/2db94c841603aea58cec31e668c7f501
(it's pasted twice so delete past half of line 40, and the print on line 39).
I can PR it if it helps.

**Comment by JarbasAI** [comment]
no longer works

401 Authorization Required

**Comment by folz** [comment]
Closing as this project is unmaintained - see https://github.com/edwardslabs/cleverwrap.py for a Python library to access the official API.

**Pull request closed without merging**
